### PR TITLE
Maxo release 2019-11-21

### PR DESCRIPTION
**Pull request by matentzn**
@lccarmody you can either close this or merge this; thought i would just do this since i have already generated the files. Up to you.

### CODE REVIEW

**Comment by matentzn** [comment]
I recommend to review the file called "maxo-base.obo" in the [diff](https://github.com/monarch-initiative/MAxO/pull/122/files)

**Comment by matentzn** [comment]
(the PR, by the way, includes a brand new ODK update, plus CHEBI import)

**Comment by LCCarmody** [comment]
I see all the term additions in the diff, but not in Protege (again). But I am on the right branch and have pulled all changes.  That's supposed to happen, right?  If so, than all is okay.  Just a little confused as to why NONE of the pattern terms are there (old biopsy terms or avoidance terms either).

**Comment by matentzn** [comment]
I am so sorry! Rookie mistake... Catalog file was incomplete after updating chebi :/ Sorry sorry. Thanks for checking and catching this! Check again and be happy :D

**Comment by LCCarmody** [comment]
Great!  I see everything! I did see one issue that I created: There was already a term for amino acid supplementation and I added it again in the pattern.  I know how to obsolete/merge terms, but I am not sure which one? Should I do before or after merging the release? 
MAXO_0000111 vs. MAXO_0010020

**Comment by matentzn** [comment]
can you fix this on master? and I will recreate the release.

**Comment by matentzn** [comment]
if it was never in maxo.owl (only in maxo-edit.owl) you dont need to obsolete. You can just remove it!

**Comment by LCCarmody** [comment]
The new term, i.e., the pattern, never existed before.  I can get rid of that one.  In the pattern, do I just replace the number with the one that already exists? Not sure what would happen to the data that is already in there? Just delete it all first?

**Comment by matentzn** [comment]
slack

**Comment by matentzn** [comment]
I dont trust myself anymore so you better check again; I think its done :P

**Pull request merged**
