### PR TITLE
Lauren edits

### PR DESCRIPTION
**Pull request by laurenechan**
add definition to smoking prevention

### CODE REVIEW

**Comment by LCCarmody** [comment]
@nicolevasilevsky There is a conflict---but I don't understand what needs to be done.

**Comment by nicolevasilevsky** [comment]
Shahim taught me how to handle conflicts, so I'll see if I can resolve this

**Comment by nicolevasilevsky** [comment]
Something weird was going on, so I just redid the edits, and am going to close this PR

**Comment by LCCarmody** [comment]
Okay. Thanks.  I normally can follow these errors, but it was definitely confusing.

**Pull request closed without merging**
