### PR TITLE
Issue 258 surgical repair

### PR DESCRIPTION
**Pull request by LCCarmody**
develop surgical repair branch

### CODE REVIEW

**Comment by LCCarmody** [comment]
@sabrinatoro For some reason it won't let me make you a reviewer. This is the Surgical repair, plastic surgery, etc. branches. There are sooooo many more terms that could be added, but I only added some of your suggestions to get the idea of structure.

**Comment by sabrinatoro** [comment]
@LCCarmody It looks good to me. There are several "single child" terms, but I don't think that it is a big issue at this point since it is clear that these single child terms won't be single anymore once we add more terms.

The only issue I have is the use of the word "normal" in the definition of 'reconstructive plastic surgery': "A medically necessary surgery performed to restore function and normal appearance of the body part."  (what is "normal"?)
BUT I don't have any suggestion for another word we could use, and I think the word "normal" is used in other terms' definitions. So I think it is ok. 

I think this PR can be merged. Thank you!!!

**Comment by LCCarmody** [comment]
@sabrinatoro Good point about the word normal. Will think about that. It reads kind of weird, but could I leave out the word 'normal' entirely? I think that would be better than 'preferred', 'typical' or other words.

**Comment by sabrinatoro** [comment]
Yes! I think the additional terms needed can be added as we come across them, using different tickets. 
I like "conventional"! I actually like it a lot! Thank you.

**Pull request merged**
