### PR TITLE
Issues fooddiet

### PR DESCRIPTION
**Pull request by LCCarmody**
Trying to clean up a few food related tickets.

### CODE REVIEW

**Comment by LCCarmody** [comment]
Adjusted the nutrition intake hierarchy and added new terms
-- MAXO_0001149 magnesium supplementation
-- MAXO_0000776 low FODMAP diet intake
-- MAXO_0000775 exclusive formula feeding
-- MAXO_0000766 low fat diet intake
-- MAXO_0000767 prescriptive diet intake
-- MAXO_0000767 small meal size recommendation
-- MAXO_0000769 prescriptive vegetarian diet intake
-- MAXO_0000770 carbohydrate controlled diet intake
-- MAXO_0000771 carbohydrate restrictive diet intake
-- MAXO_0000772 low purine diet intake
-- MAXO_0000773 dash diet intake
-- MAXO_0000762 parenteral nutrition intake
-- MAXO_0000765 central venous nutrition intake
-- MAXO_0000764 peripheral parenteral nutrition intake
-- MAXO_0000763 partial parenteral nutrition intake

Added new supplementation terms
-- MAXO:0000760 vitamin b12 supplementation
-- MAXO:0000761 vitamin b supplementation
-- MAXO:0001128 folic acid supplementation
-- MAXO:0001129 vitamin supplementation
-- MAXO:0001130 nicotinic acid supplementation
-- MAXO:0001131 pyridoxine supplementation
-- MAXO:0001133 ascorbic acid supplementation
-- MAXO:0001134 sodium pyruvate supplementation
-- MAXO:0001135 fat-soluble vitamin supplementation
-- MAXO:0001136 S-adenosyl methionine supplementation
-- MAXO:0001137 isoleucine supplementation
-- MAXO:0001138 valine supplementation
-- MAXO:0001139 calcium supplementation
-- MAXO:0001140 calcium carbonate supplementation
-- MAXO:0001141 glucose supplementation
-- MAXO:0001142 docosahexaenoic acid supplementation
-- MAXO:0001143 omega-3 fatty acid supplementation
-- MAXO:0001144 lutein supplementation
-- MAXO:0001145 ribose supplementation
-- MAXO:0001146 fluoride supplementation
-- MAXO:0001147 soluble fiber supplementation
-- MAXO:0001148 fish oil supplementation

replace MAXO:0030012 obsolete phenylalanine restricted diet intake with MAXO:0010094 phenylalanine restricted diet intake

Added new terms related to Fanconi Anemia
-- MAXO_0000745 cytogenetic analysis
-- MAXO_0000747 hematopoietic stem cell transplantation
-- MAXO_0000749 T cell-depleted hematopoietic stem cell transplantation
-- MAXO_0000759 HPV vaccination
-- MAXO_0000750 transplant conditioning
-- MAXO_0000750 clinical surveilance
-- MAXO_0000753 bone marrow examination
-- MAXO_0000752 bone marrow aspiration
-- MAXO_0000754 cellularity measurement
-- MAXO_0000755 liquid biopsy
-- MAXO_0001126avoid blood transfusion
-- MAXO_0000758 avoid unprotected sexual intercourse
-- MAXO_0000746 chromosomal breakage analysis

Terms added for pharmacotherapy usage
-- MAXO_0000744 menopausal hormone therapy
-- MAXO_0000652 ACE inhibitory therapy
-- MAXO_0000655 ACE 1 inhibitor therapy
-- MAXO_0000656 ACE 2 inhibitor therapy
-- MAXO_0000738 bile acid sequestrant therapy
-- MAXO_0000737 fibrate antilipedemic agent therapy
-- MAXO_0000739 HMG-CoA reductase inhibitor therapy
-- MAXO_0000740 nicotinic acid agent therapy (niacin therapy)
-- MAXO_0001123 potassium supplementation
-- MAXO_0000741 potassium-sparing diuretic agent therapy
-- MAXO_0001125 loop diuretic agent therapy
-- MAXO_0000743 sulfonylurea agent therapy
-- MAXO_0000164 uricosuric agent therapy
-- MAXO_0000742 thiazide diuretic agent therapy

Other term added
-- MAXO_0000748
fecal microbiota transplantation

**Comment by LCCarmody** [comment]
@laurenechan I added you as a reviewer because of the topic. If you have a chance to review this, great. If not, no worries. I will try to merge this soon because I want the terms to be there.  The 'diet' terms are still not in a pattern because I am waiting for ONS to incorporate their diet terms.   This addresses #206 #157 #94 #89 #85 #82 #66 and #58. Not all terms have been added, but many have (see comment above).

**Comment by laurenechan** [comment]
Hi Leigh, this is looking really great so far! Quick question on how we are doing ChEBI nutrition supplementation patterns. I think it looked as though we were using some the 'X atom' terms (e.g. iron atom) as the reference term for the pattern from ChEBI. As dietary supplements are not just atoms of the nutrient, are we interested in representing rather the compounds that are available for dietary supplementation (e.g. ferrous sulfate) instead? We have some of those compounds in supplement terms already like 'calcium carbonate'. 
Or are you thinking we keep the general supplementation term broad using the atom terms and then we can make specific subclasses as needed? 

I put two other small changes in as well, happy to discuss those more if we need!

**Comment by LCCarmody** [comment]
Good question.  With this release, I have added a second 'supplementation' pattern using FoodOn terms. As Foodon builds, I think we should transition from CHEBI to FOODON. Foodon will take some CHEBI terms, but put them into their hierarchy and context. Iron and calcium may require some re-working for the reasons you stated.  As I recall, I added calcium carbonate without a pattern/logical definition because it isn't in either ontology. It appears ferrous sulfate is similar. My recommendation is to add ferrous sulfate supplementation outside of the pattern for now and start a bigger discussion with the food group. Are there any others that would fall under this category?

**Comment by LCCarmody** [comment]
Sorry, I take it back. Calcium carbonate is in CHEBI and was made part of the pattern. But I still propose manual addition of ferrous sulfate supplementation and talk with FoodOn et al about how to incorporate it properly.

**Comment by laurenechan** [comment]
For supplements that have multiple components to them, I think we may need to consider most mineral supplements, so then we are talking about:
iron
selenium
calcium
potassium
sodium
phosphorus
zinc
chloride
magnesium
iodine
chromium
copper
fluoride
molybdenum
manganese

As for vitamin supplementations, we will see multiple components in each of them, but that doesn't necessarily mean that the nutrient itself has been compounded in some way as we see with the mineral supplements. 

Additionally, when we get further into dietary supplements that are nutraceutical type items (e.g. st. john's wort, echinacea) then we may need to discuss further as to how we want them represented. I do think FoodOn and ChEBI already have some of these but we may need to hash out what we want to do from a medical intervention perspective, as we have clinicians prescribing them but they're across the board as to the contents.

**Review by laurenechan — APPROVED** [review]
At this point, I think all of these changes look good and we just have a few more areas we need to discuss with the rest of the food wg team.

**Comment by LCCarmody** [comment]
I am going to accept these and then make a release, then. We can start a discussion with the food group. Other food/nutrition tickets are welcome, but I just wanted to get these out there.

**Pull request merged**
